spring.application.name=@application.name@
spring.application.version=@project.version@
spring.profiles.default=dev

# Server
server.port=${SERVER_PORT:8082}
database.host.name=${DB_HOST:localhost}
application.host=${APPLICATION_URL:http://localhost:8082}
api.prefix=api
api.version=${API_VERSION:v1}
api.base-path=/${api.prefix}/${api.version}
api.resource.users=/users
api.resource.groups=/groups

# Database
spring.jpa.open-in-view=true
spring.jpa.show-sql=false
spring.datasource.url=jdbc:postgresql://${database.host.name}:${DB_PORT:5433}/${DB_IDENTITY_NAME}
spring.datasource.username=${DB_IDENTITY_USER}
spring.datasource.password=${DB_IDENTITY_PASSWORD}

# MVC configuration
spring.mvc.static-path-pattern=/static/**
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

# Logging
logging.level.root=INFO
logging.pattern.console=[Spring] - %d{MM/dd/yyyy hh:mm:ss a} %-5level [%X{serviceName}] [corr=%X{correlationId}] [path=%X{requestPath}] [%logger{0}] - %msg%n

# --------------------------------------------------
# Keycloak
# --------------------------------------------------
keycloak.client.base-url=${KEYCLOAK_PUBLIC_URL:}
keycloak.client.public-url=${KEYCLOAK_PUBLIC_URL:}
keycloak.client.internal-url=${KEYCLOAK_INTERNAL_URL:${KEYCLOAK_PUBLIC_URL:}}
keycloak.client.realm=${KEYCLOAK_REALM_NAME:}
keycloak.client.api-client-id=${KEYCLOAK_CLIENT_ID:}
keycloak.client.admin-client-id=${KC_ADMIN_CLIENT_ID:}
keycloak.client.frontend-client-id=${KEYCLOAK_APP_CLIENT_ID:}
keycloak.client.admin-client-secret=${KC_ADMIN_CLIENT_SECRET:}

# Swagger / browser login
spring.security.oauth2.client.registration.keycloak.client-id=${keycloak.client.frontend-client-id}
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.client-name=${keycloak.client.frontend-client-id}
spring.security.oauth2.client.registration.keycloak.client-authentication-method=none
spring.security.oauth2.client.registration.keycloak.provider=keycloak
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email

spring.security.oauth2.client.provider.keycloak.issuer-uri=${keycloak.client.public-url}/realms/${keycloak.client.realm}

# Admin service account
spring.security.oauth2.client.registration.keycloak-admin.provider=keycloak-admin
spring.security.oauth2.client.registration.keycloak-admin.client-id=${keycloak.client.admin-client-id}
spring.security.oauth2.client.registration.keycloak-admin.client-secret=${keycloak.client.admin-client-secret}
spring.security.oauth2.client.registration.keycloak-admin.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.keycloak-admin.client-authentication-method=client_secret_post

# Internal Docker endpoint used to retrieve the admin token
spring.security.oauth2.client.provider.keycloak-admin.token-uri=${keycloak.client.internal-url}/realms/${keycloak.client.realm}/protocol/openid-connect/token

# Swagger & API documentation and test
springdoc.swagger-ui.oauth.client-id=${keycloak.client.frontend-client-id}
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true
springdoc.swagger-ui.oauth2-redirect-url=${application.host}/swagger-ui/oauth2-redirect.html
springdoc.api-docs.path=/openapi-docs
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.operations-sorter=alpha
springdoc.override-with-generic-response=false
springdoc.pre-loading-enabled=true

# Configuring info endpoint
info.app.name=${spring.application.name}
info.app.description=${spring.application.name} project
info.app.version=${spring.application.version}

application.issuer.ngrok=${APPLICATION_ISSUER_NGROK:}
server.cors.allowed.origins=${CORS_ALLOWED_ORIGINS:http://localhost:8082}
server.cors.allowed.methods=GET,POST,PATCH,DELETE,OPTIONS
server.cors.allowed.headers=Authorization,Content-Type,Accept
management.info.env.enabled=true
