# dev
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
management.endpoint.health.show-details=always
logging.level.it.asansonne=DEBUG
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
