spring.application.name=@application.name@
spring.application.version=@project.version@
spring.profiles.active=${PROFILE:TEST}

# Server
server.port=${SERVER_PORT:8082}
database.host.name=${PG_HOSTNAME:${HOST:localhost}}
application.host=${SCHEMA:http}://${HOST:localhost}:${server.port}
api.prefix=api
api.version=${API_VERSION:v1}
api.base-path=/${api.prefix}/${api.version}
api.resource.people=/people
api.resource.groups=/groups

people.groups.sync.on-startup=false
people.groups.sync.scheduled.enabled=false
people.groups.sync.fixed-delay-ms=3600000

# Database
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:postgresql://${database.host.name}:${PG_PORT:5432}/${DB_NAME:postgres}
spring.datasource.username=${DB_USER:}
spring.datasource.password=${DB_PASSWORD:}

# MVC configuration
spring.mvc.static-path-pattern=/static/**
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Logging
logging.level.root=INFO
logging.level.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security.oauth2=TRACE
logging.file.name=logs/adminservice.log
logging.pattern.file=[Spring] - %d{MM/dd/yyyy hh:mm:ss a} %-5level [%X{serviceName}] [corr=%X{correlationId}] [path=%X{requestPath}] [%logger{0}] - %msg%n
logging.pattern.console=[Spring] - %d{MM/dd/yyyy hh:mm:ss a} %-5level [%X{serviceName}] [corr=%X{correlationId}] [path=%X{requestPath}] [%logger{0}] - %msg%n

# --------------------------------------------------
# Keycloak
# --------------------------------------------------
keycloak.host.base-url=${KEYCLOAK_URL:http://${HOST:localhost}:5443}
keycloak.realm.name=${KEYCLOAK_REALM_NAME:${REALM:people}}
keycloak.host.realm=${keycloak.host.base-url}/realms/${keycloak.realm.name}
keycloak.host.admin=${keycloak.host.base-url}/admin/realms/${keycloak.realm.name}
keycloak.host.user=${keycloak.host.admin}/users

keycloak.client.id=${KEYCLOAK_CLIENT_ID:${KEYCLOAK_CLIENT_NAME:people-service}}
keycloak.client.secret=${KEYCLOAK_CLIENT_SECRET:}
keycloak.admin.client-id=${KC_ADMIN_CLIENT_ID:people-kc-admin}
keycloak.admin.client-secret=${KC_ADMIN_CLIENT_SECRET:}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${keycloak.host.realm}

spring.security.oauth2.client.registration.keycloak.client-id=${keycloak.client.id}
spring.security.oauth2.client.registration.keycloak.client-secret=${keycloak.client.secret}
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=password
spring.security.oauth2.client.registration.keycloak.client-name=${keycloak.client.id}
spring.security.oauth2.client.registration.keycloak.client-authentication-method=POST
spring.security.oauth2.client.registration.keycloak.provider=keycloak
spring.security.oauth2.client.provider.keycloak.issuer-uri=${keycloak.host.realm}

spring.security.oauth2.client.registration.keycloak-admin.provider=keycloak
spring.security.oauth2.client.registration.keycloak-admin.client-id=${keycloak.admin.client-id}
spring.security.oauth2.client.registration.keycloak-admin.client-secret=${keycloak.admin.client-secret}
spring.security.oauth2.client.registration.keycloak-admin.authorization-grant-type=client_credentials

application.keycloak-admin.api-url=${keycloak.host.admin}

# Swagger & API documentation and test
springdoc.swagger-ui.oauth.client-id=${keycloak.client.id}
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true
springdoc.swagger-ui.oauth2-redirect-url=${application.host}/swagger-ui/oauth2-redirect.html
springdoc.api-docs.path=/openapi-docs
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.operations-sorter=alpha
springdoc.override-with-generic-response=false
springdoc.pre-loading-enabled=true

# Configuring info endpoint
info.app.name=${spring.application.name}
info.app.description=${spring.application.name} project
info.app.version=${spring.application.version}
