spring.application.name=@application.name@
spring.application.version=0.0.1
spring.profiles.active=${PROFILE:TEST}

# Server
server.port=${SERVER_PORT:8082}
database.host.name=${PG_HOSTNAME:localhost}

# Graph QL
spring.graphql.cors.allowed-methods=POST
spring.graphql.schema.locations=classpath:graphql/${API_VERSION:v0}/
spring.graphql.schema.file-extensions=.graphql
spring.graphql.http.path=/${API_VERSION:v1}/user-service
spring.graphql.graphiql.enabled=true

# Database
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:postgresql://${database.host.name}:${POSTGRES_EXTERNAL_PORT:5432}/${POSTGRES_DB_NAME:postgres}
spring.datasource.username=${POSTGRES_USER:}
spring.datasource.password=${POSTGRES_PASSWORD:}

spring.jpa.open-in-view=true

# MVC configuration
spring.mvc.static-path-pattern=/static/**
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Logging
logging.level.root=INFO
logging.level.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security.oauth2=TRACE
logging.file.name=logs/adminservice.log
logging.pattern.file=[Spring] - %d{MM/dd/yyyy hh:mm:ss a} %-5level [%X{serviceName}] [corr=%X{correlationId}] [path=%X{requestPath}] [%logger{0}] - %msg%n
logging.pattern.console=[Spring] - %d{MM/dd/yyyy hh:mm:ss a} %-5level [%X{serviceName}] [corr=%X{correlationId}] [path=%X{requestPath}] [%logger{0}] - %msg%n

# --------------------------------------------------
# Keycloak
# --------------------------------------------------
keycloak.client-id=${KEYCLOAK_CLIENT_NAME:admin-service}
keycloak.host.realm=${KEYCLOAK_URL:http://localhost:5443/kc}/realms/${KEYCLOAK_REALM_NAME:dpms}
keycloak.host.user=${KEYCLOAK_URL}/admin/realms/${KEYCLOAK_REALM_NAME}/users
keycloak.temp.password=Password@0
spring.security.oauth2.resourceserver.jwt.issuer-uri=${keycloak.host.realm}

spring.security.oauth2.client.registration.keycloak.client-id=${keycloak.client-id}
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=password
spring.security.oauth2.client.registration.keycloak.client-name=${keycloak.client-id}
spring.security.oauth2.client.registration.keycloak.client-authentication-method=POST
spring.security.oauth2.client.registration.keycloak.provider=keycloak
spring.security.oauth2.client.provider.keycloak.issuer-uri=${keycloak.host.realm}

group.admin-group-id=${ADMIN_GROUP_ID}
group.operator-group-id=${OPERATOR_GROUP_ID}
group.super-admin-group-id=${SUPER_ADMIN_GROUP_ID}